### ISSUE TITLE
Update folder structure to match sidebar

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarWiki#167]
Some of the source folder structure is a artifact of the old wiki structure. In particular all of `docs/installing-northstar/using-northstar/` should be moved to `docs/using-northstar/`.

- [x] `README.md` #173
- [x] `direct-connect.md` #178
- [x] `launch-arguments.md` #183
- [x] `server-browser.md` #181 
- [x] `commands.md` #174
- [x] `gamemodes.md` #177
- [x] `mods.md` #175

**Comment by GeckoEidechse** [comment]
For anyone taking on this issue, I highly suggest making separate PRs for each page moved as there are a lot of links to update and limiting it to one page at a time reduces the change of missing any links and keeps diff easier/faster to PRs, ultimately speeding up the process ^^
